variables:
  ANSIBLE_VERSION: 3.2.0

stages:
  - Test
  - Build
  - Deploy

Locally:
  stage: Test
  image: ubuntu:18.04
  services:
    - docker:20.10.5-dind
  # GitLab.com variables for docker-in-docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  before_script:
    - chmod 700 .
    - apt-get update -qq
    - apt-get install -y python3-pip > /dev/null
    - pip3 install -q ansible-lint==5.0.7 ansible==$ANSIBLE_VERSION
  script:
    - ansible-lint
    - ansible-playbook --user root --inventory localhost, --connection=local
      docker-compose-app-playbook.yml
    - timeout 10s sh -c
      "until docker-compose logs print-hello-world | grep 'Hello, world!';
       do
         sleep 1;
         echo -n .;
       done"

Docker Image:
  stage: Build
  image: docker:20.10.5
  services:
    - docker:20.10.5-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
      "$CI_REGISTRY"
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]
      then
        tag=""
      else
        tag=":$CI_COMMIT_REF_NAME"
      fi
    - docker build --pull -t "$CI_REGISTRY_IMAGE${tag}"
        --build-arg ANSIBLE_VERSION .
    - docker push "$CI_REGISTRY_IMAGE${tag}"

.deployment_definition:
  before_script:
    # Remove variables that already exist in image
    - rm ansible.cfg docker-compose-app-playbook.yml
    - mkdir ~/.ssh
    - cp $ID_RSA ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
  script:
    - ansible-playbook --user "$REMOTE_USER" --inventory "$REMOTE_HOST,"
      /usr/src/app/docker-compose-app-playbook.yml
    - timeout 10s sh -c
      "until ssh $REMOTE_USER@$REMOTE_HOST sudo docker-compose
         --project-directory $CI_PROJECT_NAME logs print-hello-world |
         grep 'Hello, world!';
       do
         sleep 1;
         echo -n .;
       done"
  after_script:
    - ssh $REMOTE_USER@$REMOTE_HOST sudo docker-compose
        --project-directory $CI_PROJECT_NAME down

Remotely master:
  stage: Deploy
  image: registry.gitlab.com/trenddotfarm/deploy-docker-compose-app
  extends: .deployment_definition
  only:
    - master

Remotely:
  stage: Deploy
  image: registry.gitlab.com/trenddotfarm/deploy-docker-compose-app:$CI_COMMIT_REF_NAME
  extends: .deployment_definition
  except:
    - master
