stages:
  - Analyze code
  - Deploy

image: python:3.8.2

Lint:
  stage: Analyze code
  before_script:
    - chmod 700 .
    - pip install ansible-lint
  script:
    - ansible-lint openstack-machine.yml

Deploy:
  stage: Deploy
  before_script:
    - chmod 700 .
    - pip install openstacksdk==0.46.0 ansible==2.9.6
  script:
    - ansible-playbook openstack-machine.yml
