stages:
  - Test
  - Docker Image
  - Deploy

Simulate:
  stage: Test
  image: ubuntu:18.04
  before_script:
    - chmod 700 .
    - apt-get update -qq
    - apt-get install -y python3-pip > /dev/null
    - pip3 install ansible-lint==5.0.7 ansible==3.2.0
  script:
    - ansible-lint
    - ansible-playbook --inventory localhost, --connection=local
       -e username=root docker-compose-app-playbook.yml
    - timeout 10s sh -c
      'until docker-compose logs print-hello-world | grep -q "Hello, world!";
       do
         sleep 1;
         echo -n .;
       done'

Build:
  stage: Docker Image
  image: docker:20.10.5
  services:
    - docker:20.10.5-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
      "$CI_REGISTRY"
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]
      then
        tag=""
      else
        tag=":$CI_COMMIT_REF_NAME"
      fi
    - docker build --pull -t "$CI_REGISTRY_IMAGE${tag}" .
    - docker push "$CI_REGISTRY_IMAGE${tag}"

Trigger Stack master:
  stage: Deploy
  trigger:
    project: TrendDotFarm/stack
    strategy: depend
  variables:
    TAG_DEPLOYMENT: "latest"
    DEPLOYMENT_ONLY: "TRUE"
  only:
    - master

Trigger Stack:
  stage: Deploy
  trigger:
    project: TrendDotFarm/stack
    strategy: depend
  variables:
    TAG_DEPLOYMENT: "$CI_COMMIT_REF_NAME"
    DEPLOYMENT_ONLY: "TRUE"
  except:
    - master
