Simulate:
  image: ubuntu:18.04
  before_script:
    - apt update
    - apt install -y python-pip
    - pip install ansible-lint ansible==2.9.13
  script:
    - "! ansible-lint docker-compose-app.yml"
    - ansible-playbook docker-compose-app.yml
