Lint:
  stage: test
  image: python
  before_script:
    - chmod 700 .
    - pip install ansible-lint
  script:
    - ansible-lint docker-compose-app.yml

Simulate:
  stage: test
  image: ubuntu:18.04
  before_script:
    - chmod 700 .
    - apt update
    - apt install -y python3-pip
    - pip3 install ansible==2.10.0
  script:
    - ansible-playbook --inventory localhost, --connection=local
      docker-compose-app.yml

Trigger Stack master:
  stage: deploy
  trigger:
    project: TrendDotFarm/stack
    strategy: depend
  variables:
    TAG_DEPLOYMENT: "latest"
    DEPLOYMENT_ONLY: "TRUE"
  only:
    - master

Trigger Stack:
  stage: deploy
  trigger:
    project: TrendDotFarm/stack
    strategy: depend
  variables:
    TAG_DEPLOYMENT: $CI_COMMIT_REF_SLUG
    DEPLOYMENT_ONLY: "TRUE"
  except:
    - master
