stages:
  - Analyze code
  - Deploy

image: python:3.8.2

Lint:
  stage: Analyze code
  before_script:
    - chmod 700 .
    - pip install ansible-lint
  script:
    - ansible-lint docker-compose-app.yml
  rules:
    - allow_failure: true

Deploy:
  stage: Deploy
  before_script:
    - chmod 700 .
    - pip install ansible==2.9.7
  script:
    - ansible-playbook docker-compose-app.yml
