Lint:
  image: python
  before_script:
    - chmod 700 .
    - pip install ansible-lint
  script:
    - ansible-lint docker-compose-app.yml
  rules:
    - allow_failure: true

Simulate:
  image: ubuntu:18.04
  before_script:
    - apt update
    - apt install -y python-pip
    - chmod 700 .
    - pip install ansible==2.10.0
  script:
    - ansible-playbook docker-compose-app.yml
